name: EVDiff
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - zlib
  - openssl
  - xz
  - tk
  - sqlite
  - libffi
  - ca-certificates
  - pip:
      - einops==0.6.1
      - matplotlib==3.7.2
      - numpy==1.23.5
      - opencv-python==4.8.0.74
      - PyYAML==6.0
      - tqdm==4.65.0
      - tensorboard
      - psutil 
      - py-cpuinfo
      - pandas==2.0.3
      - scikit-image==0.21.0
      - torch==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - torchaudio==2.1.0+cu121
      - --extra-index-url https://download.pytorch.org/whl/cu121
