dataset_params:
  paths: 
    - /home/fbn/Dataset Mnist - NMnist/MNIST/Train/5

    
  paths_event: 
    - /home/fbn/Dataset Mnist - NMnist/N-MNIST/33 ms/Train/5

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model_params:
  im_channels : 1
  im_size : 28
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

train_params:
  task_name: 'default_5'
  batch_size: 80
  num_epochs: 1
  num_epochs_2: 1
  epoch_resume: -1
  num_samples : 1
  num_grid_rows : 1
  num_model: 20
  lr: 0.0001
  ckpt_name: 'Main.pth'
  ckpt_event_branch: 'Combined.pth'
  log_loss: 'default_5/training.log'
  C_log_loss: 'default_5/C_training.log'

conditional_params:
  path_conditional: '/home/fbn/Dataset Mnist - NMnist/11 ms/Test/6/944.jpg'

