dataset_params:
  paths: 
    - /home/fbn/Dataset Mnist - NMnist/Frames/0
    - /home/fbn/Dataset Mnist - NMnist/Frames/1
    - /home/fbn/Dataset Mnist - NMnist/Frames/2
    - /home/fbn/Dataset Mnist - NMnist/Frames/3
    - /home/fbn/Dataset Mnist - NMnist/Frames/4
    - /home/fbn/Dataset Mnist - NMnist/Frames/5
    - /home/fbn/Dataset Mnist - NMnist/Frames/6
    - /home/fbn/Dataset Mnist - NMnist/Frames/7
    - /home/fbn/Dataset Mnist - NMnist/Frames/8
    - /home/fbn/Dataset Mnist - NMnist/Frames/9
    
  paths_event: 
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/0
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/1
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/2
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/3
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/4
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/5
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/6
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/7
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/8
    - /home/fbn/Dataset Mnist - NMnist/11 ms/Train/9

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model_params:
  im_channels : 1
  im_size : 28
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

train_params:
  task_name: 'default'
  batch_size: 80
  num_epochs: 30
  num_samples : 1
  num_grid_rows : 1
  lr: 0.0001
  ckpt_name: 'ddpm_ckpt.pth'

conditional_params:
  path_conditional: '/home/fbn/Dataset Mnist - NMnist/11 ms/Test/6/944.jpg'

